#!/bin/bash
# Quick Testing Guide - Updated Registration Form

echo "═══════════════════════════════════════════════════════════"
echo "REGISTRATION FORM TESTING - DATABASE ALIGNMENT"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "STEP 1: Run the new database migration"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Run in backend folder:"
echo "  $ php artisan migrate"
echo ""
echo "Expected: Migration output showing new fields added to users and companies tables"
echo ""

echo "STEP 2: Start the backend server"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Terminal 1 - Backend:"
echo "  $ cd backend/recruitment-backend"
echo "  $ php artisan serve --port=8000"
echo ""
echo "Expected: 'Server running at http://127.0.0.1:8000'"
echo ""

echo "STEP 3: Start the frontend development server"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Terminal 2 - Frontend:"
echo "  $ cd frontend/recruitment-frontend"
echo "  $ npm run dev"
echo ""
echo "Expected: 'Local: http://localhost:5174'"
echo ""

echo "STEP 4: Test the registration form"
echo "────────────────────────────────────────────────────────"
echo ""
echo "1. Go to: http://localhost:5174/jobposting-login"
echo "2. Click 'Register' tab"
echo ""
echo "WHAT YOU SHOULD SEE:"
echo "  ✓ Company Name field"
echo "  ✓ Contact Person field"
echo "  ✓ Email field"
echo "  ✓ Phone field"
echo "  ✓ Website field"
echo "  ✓ Password field"
echo "  ✓ Confirm Password field"
echo "  ✓ Industry dropdown (filled with industries from database)"
echo ""

echo "STEP 5: Test with valid data"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Enter the following test data:"
echo ""
echo "  Company Name: TechCorp Solutions"
echo "  Contact Person: John Smith"
echo "  Email: john@techcorp.com"
echo "  Phone: 1234567890"
echo "  Website: https://techcorp.com"
echo "  Password: TechPass123"
echo "  Confirm Password: TechPass123"
echo "  Industry: (select any from dropdown)"
echo ""
echo "Click 'Register Company' button"
echo ""

echo "STEP 6: Verify success"
echo "────────────────────────────────────────────────────────"
echo ""
echo "You should see:"
echo "  ✓ Success alert: 'Registration successful!'"
echo "  ✓ Redirect to dashboard"
echo "  ✓ No console errors (press F12 to check)"
echo ""

echo "STEP 7: Verify data in backend database"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Terminal 3 - Database:"
echo "  $ cd backend/recruitment-backend"
echo "  $ php artisan tinker"
echo ""
echo "Check user was created:"
echo "  >>> App\\Models\\User::where('email', 'john@techcorp.com')->first()"
echo ""
echo "Expected output:"
echo "  id: 1"
echo "  name: John Smith"
echo "  email: john@techcorp.com"
echo "  phone: 1234567890"
echo "  role: recruiter"
echo "  company_id: 1"
echo ""
echo "Check company was created:"
echo "  >>> App\\Models\\Company::find(1)"
echo ""
echo "Expected output:"
echo "  id: 1"
echo "  name: TechCorp Solutions"
echo "  industry_id: (selected industry id)"
echo "  website: https://techcorp.com"
echo "  contact_person: John Smith"
echo "  contact_phone: 1234567890"
echo ""

echo "STEP 8: Test validation errors"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Test each error scenario:"
echo ""
echo "Test 1: Empty Industry"
echo "  → Submit form without selecting industry"
echo "  → Should show error: 'Please select an industry'"
echo ""
echo "Test 2: Invalid Email"
echo "  → Enter: 'notanemail'"
echo "  → Should show error: 'Please enter a valid email address'"
echo ""
echo "Test 3: Weak Password"
echo "  → Enter: 'weak'"
echo "  → Should show error: 'Password must be at least 8 characters'"
echo ""
echo "Test 4: Duplicate Email"
echo "  → Register with john@techcorp.com again"
echo "  → Should show error: 'This email is already registered'"
echo ""

echo "STEP 9: Test on fresh database"
echo "────────────────────────────────────────────────────────"
echo ""
echo "To test with a fresh database:"
echo ""
echo "  $ php artisan migrate:fresh"
echo "  $ php artisan serve --port=8000"
echo ""
echo "This will:"
echo "  ✓ Reset all tables"
echo "  ✓ Run all migrations"
echo "  ✓ Apply new fields to users and companies tables"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "TESTING CHECKLIST"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✓ Industries dropdown loads with data"
echo "✓ All form fields are visible"
echo "✓ Form validation works (invalid data rejected)"
echo "✓ Valid registration succeeds"
echo "✓ User created with phone field"
echo "✓ Company created with website, contact_person, contact_phone"
echo "✓ No localStorage data stored (data only in backend)"
echo "✓ Success redirect to dashboard works"
echo "✓ Duplicate email prevention works"
echo "✓ Password strength validation works"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "KEY POINTS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Industries must exist in database before registration"
echo "   → Seed them or create via artisan command if needed"
echo ""
echo "2. All user/company data is now stored in backend only"
echo "   → No localStorage saves (secure)"
echo ""
echo "3. Form collects all database fields:"
echo "   → User: name, email, phone, password, role"
echo "   → Company: name, website, contact info, industry_id"
echo ""
echo "4. Migration adds missing fields:"
echo "   → phone to users table"
echo "   → website, contact_person, contact_email, contact_phone to companies"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "Ready to test! Follow the steps above."
echo "═══════════════════════════════════════════════════════════"
echo ""
